### ISSUE TITLE
Estrutura inicial do repositório

### ISSUE THREAD

**Issue by wkrueger** [wkrueger/techjobs_api#3]
Bastante coisa aqui 🙃

Se souber de algum pacote interessante pra adicionar, sugestões são bem vindas!

 - Usar gerenciador de pacotes pipenv
 - Inicializar projeto django
 - Nomes sugeridos de pastas do django: `techjobs_proj` e `techjobs_app`
 - Instalar e configurar `django_environ` (https://django-environ.readthedocs.io/en/latest/)
 - Adicionar um docker-compose pra rodar o postgres local de desenvolvimento (conteúdo abaixo)
 - Instalar o `graphene-django` e adicionar uma rota inicial para o "graphiQL" (*)

(o graphiQL é uma interface web do graphQL pra consultar quais ações a API expõe)

```
version: "3.8"

services:
  techjobs-postgres:
    image: postgres:13
    restart: "no"
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - "techjobs-postgres:/var/lib/postgresql/data"

volumes:
  djtest-pg:
```
